### ISSUE TITLE
How to Run the VBA expressions test

### ISSUE THREAD

**Issue by ghost** [ws-garcia/ws-garcia#1]
Hello Wilfred,
I wish to ask you how to run the VBA expression code. I'm trying to use TestRunner.xlsm but for each module, I receive an error maybe I've not understood properly how it works. Do you have a trivial test with a text box where I type the expression and I get the result. Thanks in advance and sorry if I contact you here.
Regards

**Comment by ws-garcia** [comment]
Greetings dear, you don't have to apologize for contacting me, that is the main purpose of this site.

I am sorry to inform you that to run the tests you need to install the free [Rubberduck add-on](https://rubberduckvba.com/). But don't worry, as soon as possible I will be sending you an Excel workbook with a form so you can write the expressions you want to evaluate.

It is a pleasure and an honor to know that you are interested in collaborating with the development of VBA Expressions!

Edit:
I am attaching an [Excel workbook](https://drive.google.com/file/d/1VVCP1CRkZNPf6aqyEOeUjH-SEchKWkxz/view?usp=drivesdk) to this issue. In the Excel ribbon you will find a Tab named `VBA expressions`, in it you will see a button with which you can launch a Userform and play with the evaluator.

Regards

**Comment by ghost** [comment]
Top Wilfred :-) Great Job.

Thanks a lot for your kind support.

Best Regards
Carlo
